# Generated by Django 4.2.3 on 2023-07-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Работник", "verbose_name_plural": "Работники"},
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(max_length=100, verbose_name="Департамент"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.CharField(max_length=100, verbose_name="Дата приема"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.CharField(max_length=100, verbose_name="Заработная плата"),
        ),
    ]
