# Generated by Django 4.2.3 on 2023-07-23 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employees_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
