# Generated by Django 4.2.3 on 2023-07-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "employees_api",
            "0002_alter_employee_options_alter_employee_department_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.CharField(max_length=10, verbose_name="Дата приема"),
        ),
    ]
