# Generated by Django 4.2.3 on 2023-07-19 19:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees_api", "0003_alter_employee_hire_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="tasks",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=150),
                blank=True,
                default=[],
                size=None,
                verbose_name="Задачи",
            ),
        ),
    ]
